services:
  pyrsia:
    image: pyrsia/node
    build:
      context: .
      target: node
    command: [ "/tmp/entrypoint.sh", "--host", "0.0.0.0", "--listen", "/ip4/0.0.0.0/tcp/44000" ]
    stdin_open: true
    ports:
      - "7888:7888"
    volumes:
      - "pyrsia:/tmp"

volumes:
  pyrsia:
