services:
  pyrsia:
    environment:
      # - RUST_LOG=debug # uncomment to turn on debug
      - PYRSIA_BOOTDNS=boot.pyrsia.link
    image: pyrsia/node
    build:
      context: .
      target: node
    stdin_open: true
    ports:
      - "7888:7888"
    volumes:
      - "pyrsia:/tmp"

volumes:
  pyrsia:
