services:
  pyrsia:
    image: pyrsia/node
    build:
      target: node
    command: ["-p", "7878"]
    stdin_open: true
    ports:
      - "7878:7878"
    volumes:
      - "pyrsia:/tmp"

volumes:
  pyrsia:
