services:
  pyrsia:
    image: pyrsia/node
    build:
      context: .
      target: node
    command: ["-H" , "0.0.0.0", "-p", "7888"]
    stdin_open: true
    ports:
      - "7888:7888"
    volumes:
      - "pyrsia:/tmp"

volumes:
  pyrsia:
