---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "winrepo-nginx.name" . }}
spec:
  selector:
    app: {{ include "winrepo-nginx.name" . }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: NodePort
