---
###############
# Rules by id #
###############
MD007:
  indent: 2                   # Unordered list indentation
MD013: false                  # Line length 80 is far to short
MD026:
  punctuation: ".,;:!。，；:"  # List of not allowed
MD029: false                  # Ordered list item prefix
MD033: false                  # Allow inline HTML
MD051: false                  # allow #GitHub-style-anchor-links
