#[cfg(test)]
mod tests {
    use pyrsia_client_lib::signed::{create_key_pair, JwsSignatureAlgorithms, Signed};
    use signed_struct::signed_struct;

    #[signed_struct]
    struct Foo<'a> {
        foo: String,
        bar: u32,
        zot: &'a str,
    }

    #[test]
    fn test_generated_methods() -> Result<(), anyhow::Error> {
        let key_pair = create_key_pair(JwsSignatureAlgorithms::RS512)?;

        //Test methods of Foo generated by [signed_struct]
        let mut foo: Foo = Foo::new(String::from("abc"), 234, &"qwerty");

        foo.sign_json(JwsSignatureAlgorithms::RS512, &key_pair.private_key, &key_pair.public_key)?;
        foo.verify_signature()?;
        Ok(())
    }
}
