#[cfg(test)]
mod tests {
    use pyrsia_client_lib::signed::{create_key_pair, JwsSignatureAlgorithms, Signed};
    use signed_struct::signed_struct;

    #[signed_struct]
    struct Foo<'a> {
        foo: String,
        bar: u32,
        zot: &'a str,
    }

    #[test]
    fn test_generated_methods() -> Result<(), anyhow::Error> {
        let key_pair = create_key_pair(JwsSignatureAlgorithms::RS512)?;
        let foo_value: String = String::from("abc");
        let foo_value_clone = foo_value.clone();
        let bar_value: u32 = 234;
        let zot_value: &str = "qwerty";

        //Test methods of Foo generated by [signed_struct]
        let mut foo: Foo = Foo::new(foo_value, bar_value, zot_value);

        foo.sign_json(
            JwsSignatureAlgorithms::RS512,
            &key_pair.private_key,
            &key_pair.public_key,
        )?;
        foo.verify_signature()?;
        assert_eq!(foo_value_clone, *foo.foo()); // The * is needed because the getters add a & to the type.
        assert_eq!(bar_value, *foo.bar());
        assert_eq!(zot_value, *foo.zot());
        Ok(())
    }
}
