---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kube-system
  name: {{ printf "%s-service-reader" (include "pyrsia-node.name" .) }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-service-reader" (include "pyrsia-node.name" .) }}
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: {{ printf "%s-service-reader" (include "pyrsia-node.name" .) }}
    # Reference to upper's `metadata.namespace`
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ printf "%s-service-reader" (include "pyrsia-node.name" .) }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-service-reader" (include "pyrsia-node.name" .) }}
  namespace: {{ .Release.Namespace }}
---
