apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pyrsia-keys
data:
  ed25519.ser: |
  {{ .Values.keys.p2p | indent 2 }}
  blockchain_ed25519.ser: |
  {{ .Values.keys.blockchain | indent 2 }}
