---
kind: Service
apiVersion: v1
metadata:
  name: pyrsia-node-0
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pyrsia-node-0.pyrsia.link  
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: pyrsia-node-0
  ports:
    - port: 80
      targetPort: 7888
      protocol: TCP
      name: pyrsia
    - port: 44000
      targetPort: 44000
      protocol: TCP
      name: p2p
---
kind: Service
apiVersion: v1
metadata:
  name: pyrsia-node-1
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pyrsia-node-1.pyrsia.link    
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: pyrsia-node-1
  ports:
    - port: 80
      targetPort: 7888
      protocol: TCP
      name: pyrsia
    - port: 44000
      targetPort: 44000
      protocol: TCP
      name: p2p
---
kind: Service
apiVersion: v1
metadata:
  name: pyrsia-node-2
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pyrsia-node-2.pyrsia.link    
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: pyrsia-node-2
  ports:
    - port: 80
      targetPort: 7888
      protocol: TCP
      name: pyrsia
    - port: 44000
      targetPort: 44000
      protocol: TCP
      name: p2p
---
