---
kind: Service
apiVersion: v1
metadata:
  name: {{ printf "%s-0" (include "pyrsia-node.name" .) }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ printf "%s-0.%s" (include "pyrsia-node.name" .) (.Values.dnsname | default "pyrsia.link")  }} 
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: {{ printf "%s-0" (include "pyrsia-node.name" .) }}
  ports:
    - port: 80
      targetPort: 7888
      protocol: TCP
      name: pyrsia
    - port: 44000
      targetPort: 44000
      protocol: TCP
      name: p2p
---
kind: Service
apiVersion: v1
metadata:
  name: {{ printf "%s-1" (include "pyrsia-node.name" .) }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ printf "%s-1.%s" (include "pyrsia-node.name" .) (.Values.dnsname | default "pyrsia.link")  }}
    external-dns.alpha.kubernetes.io/ttl: "60"     
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: {{ printf "%s-1" (include "pyrsia-node.name" .) }}
  ports:
    - port: 80
      targetPort: 7888
      protocol: TCP
      name: pyrsia
    - port: 44000
      targetPort: 44000
      protocol: TCP
      name: p2p
---
kind: Service
apiVersion: v1
metadata:
  name: {{ printf "%s-2" (include "pyrsia-node.name" .) }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ printf "%s-2.%s" (include "pyrsia-node.name" .) (.Values.dnsname | default "pyrsia.link") }} 
    external-dns.alpha.kubernetes.io/ttl: "60"   
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: {{ printf "%s-2" (include "pyrsia-node.name" .) }}
  ports:
    - port: 80
      targetPort: 7888
      protocol: TCP
      name: pyrsia
    - port: 44000
      targetPort: 44000
      protocol: TCP
      name: p2p
---
