apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pyrsia-sc
{{- if contains "eks" (.Capabilities.KubeVersion.Version | toString) }}
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
{{- end }}
{{- if contains "gke" (.Capabilities.KubeVersion.Version | toString) }}
provisioner: pd.csi.storage.gke.io
allowVolumeExpansion: true
parameters:
  type: pd-standard
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
{{- end }}
