apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pyrsia-sc
{{- if eq .Values.k8s_provider "eks" }}
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
{{- end }}
{{- if eq .Values.k8s_provider "gke" }}
provisioner: pd.csi.storage.gke.io
allowVolumeExpansion: true
parameters:
  type: pd-standard
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
{{- end }}
