---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: pyrsia-staging
  region: us-east-1
cloudWatch:
  clusterLogging:
    enableTypes:
      - audit
      - authenticator
managedNodeGroups:
  - name: ng-1
    amiFamily: AmazonLinux2
    instanceSelector:
      cpuArchitecture: x86_64
      memory: 2GiB
      vCPUs: 2
    instanceTypes:
      - t3.small
      - t3a.small
iam:
  withOIDC: true
addons:
  - name: aws-ebs-csi-driver
    version: v1.13.0-eksbuild.3
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
