[package]
name = "artifact_manager"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "lib" ]
name = "artifact_manager"
path = "src/artifact_manager.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
