---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "brewrepo-nginx.name" . }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ include "brewrepo-nginx.name" . }}
    networking.gke.io/managed-certificates: managed-cert-brewrepo
    networking.gke.io/v1beta1.FrontendConfig: {{ include "brewrepo-nginx.name" . }}
spec:
  defaultBackend:
    service:
      name: {{ include "brewrepo-nginx.name" . }}
      port:
        number: 80
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ include "brewrepo-nginx.name" . }}
spec:
  redirectToHttps:
    enabled: true
