name: Build Pyrsia Node Docker Image
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker buildx bake node
