---
name: Demo Script

on:
  push:

jobs:
  installation:
    runs-on: ubuntu-20.04
    steps:
      - name: Run Install
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://repo.pyrsia.io/repos/Release.key |  gpg --dearmor  > pyrsia.gpg
          sudo install -o root -g root -m 644 pyrsia.gpg /etc/apt/trusted.gpg.d/
          rm pyrsia.gpg
          echo "deb https://repo.pyrsia.io/repos/nightly focal main" | sudo tee -a /etc/apt/sources.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y pyrsia
        shell: bash
      - name: Run Pyrsia
        run: |
          pyrsia --version
        shell: bash
