name: Docs Linting 
on:
  push:
  pull_request:
    paths:
      - .github/workflows/doc-lint.yml
      - '**/*.md'
      - '**/*.mdx'
      
jobs:
  markdown-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: github/super-linter/slim@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MARKDOWN_CONFIG_FILE: .markdownlint.yaml
          FILTER_REGEX_INCLUDE: .*\.[md|mdx]
          FILTER_REGEX_EXCLUDE: pull_request_template\.md
          VALIDATE_EDITORCONFIGE: false
          VALIDATE_GITLEAKS: false
          VALIDATE_NATURAL_LANGUAGE: false
          MULTI_STATUS: false

  inclusive-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run woke
        run: |
            curl -sSfL https://git.io/getwoke | bash -s --
            bin/woke --exit-1-on-failure
        shell: bash
