name: Docs Linting 
on:
  pull_request:
    paths: |
      **/*.md
      **/*.mdx
      
jobs:
  markdown-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gem install mdl
      - run: mdl docs/

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1

  inclusive-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run woke
        run: |
            curl -sSfL https://git.io/getwoke | bash -s --
            bin/woke --exit-1-on-failure
        shell: bash
